development:
  adapter: postgresql
  database: enterprise_mti_development
  username: enterprise_mti
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  database: enterprise_mti_test
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: enterprise_mti_production
  pool: 5
  username: enterprise_mti
  password:

cucumber:
  <<: *test
